version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 12
  build:
    commands:
      - sdk install gradle
      - sam build   --template template.yaml  --build-dir .aws-sam/build
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged-template.yaml --s3-bucket greenhills-server

artifacts:
  files:
    - packaged-template.yml

cache:
  paths:
    - '/root/.m2/**/*'