version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 12
  build:
    commands:
      - cd ContactDetailsFunction
      - gradle build

cache:
  paths:
    - '/root/.m2/**/*'