version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 12
  build:
    commands:
      - cd ContactDetailsFunction
      - gradle build

artifacts:
  files:
    - ContactDetailsFunction/build/libs/ContactDetailsFunction-1.0-SNAPSHOT.jar
  name: greenhills-server-contct-details-$(date +%Y-%m-%d)
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'