version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 12

  pre_build:
    commands:
      - cd ContactDetailsFunction
      - gradle wrapper
      - cd ..

  build:
    commands:
      - sam build   --template template.yaml  --build-dir .aws-sam/build

  post_build:
    commands:
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged-template.yaml --s3-bucket greenhills-server
      - echo "SAM packaging completed on `date`"

artifacts:
  files:
    - packaged-template.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'